### ISSUE TITLE
deltachat-core is deprecated

### ISSUE THREAD

**Issue by Ethanol6** [ccpp/deltachat-purple#1]
New library is here: https://github.com/deltachat/deltachat-core-rust

Would be awesome to see this project keep going. I'd help out if I knew how.

**Comment by ccpp** [comment]
Sorry, this project is discontinued and does not even implement deltachat.
There are other projects like [mongoman's](https://github.com/mogorman/purple-deltachat) or the one [linked bt pidgin themselves](https://code.ur.gs/lupine/purple-plugin-delta) - but to be honest, both links do not seem more promising than my project ;)
